### ISSUE TITLE
main.py: error: argument --model: expected one argument

### ISSUE THREAD

**Issue by zhang-deep** [mhashas/Document-Unwarping#4]
![企业微信截图_20200716203644](https://user-images.githubusercontent.com/62748383/87671552-1c34ae80-c7a4-11ea-8037-9715805d9ba0.png)

**Comment by mhashas** [comment]
Please check the[parser options](https://github.com/mhashas/Document-Image-Unwarping-pytorch/blob/master/parser_options.py). Try running the code from main.py directly, not from the bash script
